package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/openexec/openexec/internal/approval"
	"github.com/openexec/openexec/internal/infra"
	"github.com/openexec/openexec/internal/knowledge"
	"github.com/openexec/openexec/internal/mcp"
	"github.com/openexec/openexec/internal/memory"
	"github.com/openexec/openexec/internal/project"
	"github.com/openexec/openexec/pkg/plugin"
	"github.com/spf13/cobra"
)

var (
	mcpServeMode      string
	mcpServeWorkspace string
	mcpServeProfile   string
)

// resolveServeRoot picks the one workspace root every repository-scoped
// resource must use: the flag, else WORKSPACE_ROOT, else the working
// directory. It mirrors the MCP server's own precedence so the symbol index,
// project modules, infra allowlist and approvals database cannot disagree —
// once --workspace is a security boundary, a resource resolved from cwd is a
// hole in it.
func resolveServeRoot(flagValue string) string {
	if flagValue != "" {
		return flagValue
	}
	if env := os.Getenv("WORKSPACE_ROOT"); env != "" {
		return env
	}
	cwd, _ := os.Getwd()
	return cwd
}

// validateServeMode fails closed on an unknown permission mode.
//
// NewToolBroker normalizes anything unrecognized to auto-edit, which permits
// git_apply_patch. That is a sane default for an omitted value but a dangerous
// one for a misspelled flag: `--mode sugest` would silently widen a session
// the caller intended to be read-only.
func validateServeMode(value string) error {
	switch value {
	case "", string(mcp.ModeSuggest), string(mcp.ModeAutoEdit), string(mcp.ModeFullAuto):
		return nil
	}
	return fmt.Errorf("invalid --mode %q: expected %s, %s or %s",
		value, mcp.ModeSuggest, mcp.ModeAutoEdit, mcp.ModeFullAuto)
}

func init() {
	// Flags, not only environment: a caller that spawns this process as an MCP
	// server (Agent Console) pins the permission mode as a security control,
	// and a control must not depend on whether the spawning client propagates
	// an env map. Argv always survives.
	mcpServeCmd.Flags().StringVar(&mcpServeMode, "mode", "",
		"permission mode: suggest, auto-edit, or danger-full-access (overrides OPENEXEC_MODE)")
	mcpServeCmd.Flags().StringVar(&mcpServeWorkspace, "workspace", "",
		"workspace root to serve (overrides WORKSPACE_ROOT and the working directory)")
	mcpServeCmd.Flags().StringVar(&mcpServeProfile, "profile", "",
		"tool profile: empty for the full light-mode surface, or 'symbols' for repository lookup only")
	rootCmd.AddCommand(mcpServeCmd)
}

var mcpServeCmd = &cobra.Command{
	Use:   "mcp-serve",
	Short: "Run the OpenExec MCP server (signals + story backlog for light-mode clients)",
	Long: `Run the OpenExec MCP server over stdio.

Exposes the orchestrator control plane (openexec_signal, openexec_result) and
the story backlog (backlog_list_stories, backlog_get_story, backlog_claim_story,
backlog_complete_task, backlog_complete_story) plus project memory (memory_read).

This is the light-mode entry point: an external MCP client such as Claude Code
can read the backlog generated by the heavy pipeline and work it one story at
a time, without booting the OpenExec daemon. See docs/LIGHT_MODE.md.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if mcpServeProfile != "" && mcpServeProfile != "symbols" {
			return fmt.Errorf("invalid --profile %q: expected 'symbols' or empty", mcpServeProfile)
		}
		if err := validateServeMode(mcpServeMode); err != nil {
			return err
		}
		// One root for every repository-scoped resource below.
		workDir := resolveServeRoot(mcpServeWorkspace)
		// The server prefers WORKSPACE_ROOT over WorkDir, so an inherited value
		// would otherwise silently outrank the root resolved here.
		if err := os.Setenv("WORKSPACE_ROOT", workDir); err != nil {
			return err
		}
		serveMode := mcpServeMode
		if serveMode == "" {
			serveMode = os.Getenv("OPENEXEC_MODE")
			// An inherited environment is not a caller's explicit choice, so a
			// bad value there falls back rather than failing the server.
			if validateServeMode(serveMode) != nil {
				fmt.Fprintf(os.Stderr, "ignoring invalid OPENEXEC_MODE %q\n", serveMode)
				serveMode = ""
			}
		}
		if mcpServeProfile == "symbols" && serveMode == "" {
			// A lookup-only server has no use for patch capability.
			serveMode = string(mcp.ModeSuggest)
		}
		srv, err := mcp.NewServerWithConfig(os.Stdin, os.Stdout, mcp.ServerConfig{
			WorkDir: workDir,
			Mode:    serveMode,
		})
		if err != nil {
			fmt.Fprintf(os.Stderr, "MCP server error: %v\n", err)
			fmt.Fprintf(os.Stderr, "Hint: Set WORKSPACE_ROOT env var or run from a valid project directory\n")
			return err
		}

		// Wire the memory_read loader (composition root injects it so the MCP
		// server does not import internal/memory).
		srv.SetMemoryLoader(func(root string) (string, error) {
			return memory.NewMemorySystem(root).LoadMerged()
		})

		// Repository symbol tools: pointer lookup over the knowledge graph, so
		// an agent locates code by symbol instead of grepping and reading whole
		// files. Only wired for an initialized workspace — knowledge.NewStore
		// would otherwise create .openexec in a directory the user never
		// initialized, and the tools are advertised only when an index exists.
		//
		// The root comes from the server, not from workDir: the server prefers
		// WORKSPACE_ROOT over the working directory, and a client that spawns
		// this process from an unrelated cwd (Agent Console does) would
		// otherwise be told there is no index while the server happily scopes
		// itself to the real one.
		symbolsOnly := mcpServeProfile == "symbols"
		if graphRoot := symbolIndexRoot(srv.WorkspaceRoots()); graphRoot != "" {
			kStore, kerr := knowledge.NewStore(graphRoot)
			if kerr != nil {
				// A missing index must not take down the backlog and control
				// plane: degrade to no symbol tools and say why.
				fmt.Fprintf(os.Stderr, "symbol tools unavailable: %v\n", kerr)
			} else {
				if symbolsOnly {
					// Lookup advertised as cheaper than grep must not become a
					// synchronous full extraction; report drift instead.
					kStore.SetRefreshOnRead(false)
				}
				srv.SetSymbolIndex(newGraphSymbolIndex(kStore))
			}
		}

		// The symbols profile stops here: no modules, no infra allowlist, no
		// approval gate, no backlog or skill writes. Everything below widens the
		// surface, and this profile exists precisely to not have it.
		if symbolsOnly {
			srv.SetSymbolsOnly(true)
			return srv.Serve()
		}

		// Module gates (H1): the composition root decides which optional modules
		// register, so core stays module-free and paid modules can be turned off
		// by config / entitlement. A missing project config (light-mode on an
		// uninitialized dir) leaves the zero value — every module enabled.
		var modules project.ModulesConfig
		if pc, perr := project.LoadProjectConfig(workDir); perr == nil && pc != nil {
			modules = pc.Modules
		}

		// Register MCP tool providers contributed by modules (pkg/plugin). A
		// module in its own build registers via plugin.RegisterMCPProvider from an
		// init(); each is gated by the project's `modules:` config. The
		// open-source core registers none — the seam keeps core module-free.
		for _, p := range plugin.MCPProviders() {
			if ok, reason := modules.ShouldLoad(p.Name); !ok {
				fmt.Fprintf(os.Stderr, "module %q not loaded: %s\n", p.Name, reason)
				continue
			}
			if rerr := srv.RegisterProvider(p.New()); rerr != nil {
				fmt.Fprintf(os.Stderr, "module %q registration failed: %v\n", p.Name, rerr)
				return rerr
			}
		}

		// Infra tools (SRE command registry): gated by the module config AND, when
		// enabled, by the presence of an operator-written .openexec/infra.yaml. A
		// malformed allowlist fails the server loudly — a security config must
		// never half-load.
		var infraReg *infra.Registry
		if sreEnabled, sreReason := modules.ShouldLoad("sre"); !sreEnabled {
			fmt.Fprintf(os.Stderr, "sre module not loaded: %s\n", sreReason)
		} else {
			infraReg, err = infra.LoadRegistry(workDir)
			if err != nil {
				fmt.Fprintf(os.Stderr, "infra allowlist error: %v\n", err)
				return err
			}
		}
		if infraReg != nil {
			srv.SetInfraRegistry(infraReg)
			// The composition root injects the production runner (the MCP server
			// no longer imports internal/infra to construct one).
			srv.SetInfraRunner(&infra.ExecRunner{})

			// Persistent approval gate (Phase 3): apply-class infra commands
			// block on the shared approvals DB until an operator signs off
			// via `openexec approve list/yes/no --local` or an
			// OPENEXEC_OPERATOR_SESSION=1 mcp-serve session.
			waitTimeout := approval.DefaultWaitTimeout
			if v := os.Getenv("OPENEXEC_APPROVAL_WAIT"); v != "" {
				d, perr := time.ParseDuration(v)
				if perr != nil {
					fmt.Fprintf(os.Stderr, "invalid OPENEXEC_APPROVAL_WAIT %q: %v\n", v, perr)
					return perr
				}
				waitTimeout = d
			}
			gate, mgr, gerr := approval.OpenPersistentGate(
				filepath.Join(workDir, ".openexec", "approvals.db"), workDir, waitTimeout)
			if gerr != nil {
				fmt.Fprintf(os.Stderr, "approvals store error: %v\n", gerr)
				return gerr
			}
			// Apply-class infra tools must never be auto-approved by the
			// seeded risk-based policy (it auto-approves low risk only;
			// unknown tools default to medium — pin them to high anyway).
			if rerr := gate.SetToolRisk(approval.RiskLevelHigh,
				"ansible_run_playbook", "salt_apply_state", "terraform_apply"); rerr != nil {
				return rerr
			}
			mcp.SetApprovalGateForServer(srv, gate)
			srv.SetApprovalManager(mgr)
		}

		return srv.Serve()
	},
}
