package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/openexec/openexec/internal/approval"
	"github.com/openexec/openexec/internal/governance/mcpgov"
	"github.com/openexec/openexec/internal/infra"
	"github.com/openexec/openexec/internal/mcp"
	"github.com/openexec/openexec/internal/memory"
	"github.com/openexec/openexec/internal/project"
	"github.com/spf13/cobra"
)

func init() {
	rootCmd.AddCommand(mcpServeCmd)
}

var mcpServeCmd = &cobra.Command{
	Use:   "mcp-serve",
	Short: "Run the OpenExec MCP server (signals + story backlog for light-mode clients)",
	Long: `Run the OpenExec MCP server over stdio.

Exposes the orchestrator control plane (openexec_signal, openexec_result) and
the story backlog (backlog_list_stories, backlog_get_story, backlog_claim_story,
backlog_complete_task, backlog_complete_story) plus project memory (memory_read).

This is the light-mode entry point: an external MCP client such as Claude Code
can read the backlog generated by the heavy pipeline and work it one story at
a time, without booting the OpenExec daemon. See docs/LIGHT_MODE.md.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		// Get workspace from current directory or WORKSPACE_ROOT
		workDir, _ := os.Getwd()
		srv, err := mcp.NewServerWithConfig(os.Stdin, os.Stdout, mcp.ServerConfig{
			WorkDir: workDir,
			Mode:    os.Getenv("OPENEXEC_MODE"),
		})
		if err != nil {
			fmt.Fprintf(os.Stderr, "MCP server error: %v\n", err)
			fmt.Fprintf(os.Stderr, "Hint: Set WORKSPACE_ROOT env var or run from a valid project directory\n")
			return err
		}

		// Wire the memory_read loader (composition root injects it so the MCP
		// server does not import internal/memory).
		srv.SetMemoryLoader(func(root string) (string, error) {
			return memory.NewMemorySystem(root).LoadMerged()
		})

		// Module gates (H1): the composition root decides which optional modules
		// register, so core stays module-free and paid modules can be turned off
		// by config / entitlement. A missing project config (light-mode on an
		// uninitialized dir) leaves the zero value — every module enabled.
		var modules project.ModulesConfig
		if pc, perr := project.LoadProjectConfig(workDir); perr == nil && pc != nil {
			modules = pc.Modules
		}

		// Governance MCP tools ship with the governance module; register them so
		// core exposes them without importing governance.
		if ok, reason := modules.ShouldLoad("governance"); ok {
			if rerr := srv.RegisterProvider(mcpgov.New()); rerr != nil {
				fmt.Fprintf(os.Stderr, "governance module registration failed: %v\n", rerr)
				return rerr
			}
		} else {
			fmt.Fprintf(os.Stderr, "governance module not loaded: %s\n", reason)
		}

		// Infra tools (SRE command registry): gated by the module config AND, when
		// enabled, by the presence of an operator-written .openexec/infra.yaml. A
		// malformed allowlist fails the server loudly — a security config must
		// never half-load.
		var infraReg *infra.Registry
		if sreEnabled, sreReason := modules.ShouldLoad("sre"); !sreEnabled {
			fmt.Fprintf(os.Stderr, "sre module not loaded: %s\n", sreReason)
		} else {
			infraReg, err = infra.LoadRegistry(workDir)
			if err != nil {
				fmt.Fprintf(os.Stderr, "infra allowlist error: %v\n", err)
				return err
			}
		}
		if infraReg != nil {
			srv.SetInfraRegistry(infraReg)
			// The composition root injects the production runner (the MCP server
			// no longer imports internal/infra to construct one).
			srv.SetInfraRunner(&infra.ExecRunner{})

			// Persistent approval gate (Phase 3): apply-class infra commands
			// block on the shared approvals DB until an operator signs off
			// via `openexec approve list/yes/no --local` or an
			// OPENEXEC_OPERATOR_SESSION=1 mcp-serve session.
			waitTimeout := approval.DefaultWaitTimeout
			if v := os.Getenv("OPENEXEC_APPROVAL_WAIT"); v != "" {
				d, perr := time.ParseDuration(v)
				if perr != nil {
					fmt.Fprintf(os.Stderr, "invalid OPENEXEC_APPROVAL_WAIT %q: %v\n", v, perr)
					return perr
				}
				waitTimeout = d
			}
			gate, mgr, gerr := approval.OpenPersistentGate(
				filepath.Join(workDir, ".openexec", "approvals.db"), workDir, waitTimeout)
			if gerr != nil {
				fmt.Fprintf(os.Stderr, "approvals store error: %v\n", gerr)
				return gerr
			}
			// Apply-class infra tools must never be auto-approved by the
			// seeded risk-based policy (it auto-approves low risk only;
			// unknown tools default to medium — pin them to high anyway).
			if rerr := gate.SetToolRisk(approval.RiskLevelHigh,
				"ansible_run_playbook", "salt_apply_state", "terraform_apply"); rerr != nil {
				return rerr
			}
			mcp.SetApprovalGateForServer(srv, gate)
			srv.SetApprovalManager(mgr)
		}

		return srv.Serve()
	},
}
