package release

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// ChangelogGenerator generates release documentation.
type ChangelogGenerator struct {
	manager *Manager
}

// NewChangelogGenerator creates a new changelog generator.
func NewChangelogGenerator(manager *Manager) *ChangelogGenerator {
	return &ChangelogGenerator{manager: manager}
}

// ChangelogOptions configures changelog generation.
type ChangelogOptions struct {
	// Include git commit links
	IncludeCommits bool

	// Include task details
	IncludeTasks bool

	// Include approval information
	IncludeApprovals bool

	// Base URL for linking (e.g., "https://github.com/org/repo")
	RepoURL string

	// Date format for timestamps
	DateFormat string
}

// DefaultChangelogOptions returns default options.
func DefaultChangelogOptions() *ChangelogOptions {
	return &ChangelogOptions{
		IncludeCommits:   true,
		IncludeTasks:     true,
		IncludeApprovals: false,
		DateFormat:       "2006-01-02",
	}
}

// Generate generates a changelog for the current release.
func (g *ChangelogGenerator) Generate(opts *ChangelogOptions) (string, error) {
	if opts == nil {
		opts = DefaultChangelogOptions()
	}

	release := g.manager.GetRelease()
	if release == nil {
		return "", fmt.Errorf("no release defined")
	}

	var sb strings.Builder

	// Header
	sb.WriteString(fmt.Sprintf("# %s\n\n", release.Name))
	sb.WriteString(fmt.Sprintf("**Version:** %s\n", release.Version))
	sb.WriteString(fmt.Sprintf("**Date:** %s\n", release.CreatedAt.Format(opts.DateFormat)))

	if release.Description != "" {
		sb.WriteString(fmt.Sprintf("\n%s\n", release.Description))
	}

	// Git information
	if release.Git != nil {
		sb.WriteString("\n## Git Information\n\n")
		sb.WriteString(fmt.Sprintf("- **Branch:** `%s`\n", release.Git.Branch))
		if release.Git.Tag != "" {
			sb.WriteString(fmt.Sprintf("- **Tag:** `%s`\n", release.Git.Tag))
		}
		if release.Git.BaseBranch != "" {
			sb.WriteString(fmt.Sprintf("- **Base:** `%s`\n", release.Git.BaseBranch))
		}
	}

	// Group stories by type
	features := g.getStoriesByType(release.Stories, StoryTypeFeature)
	bugfixes := g.getStoriesByType(release.Stories, StoryTypeBugfix)
	chores := g.getStoriesByType(release.Stories, StoryTypeChore)
	refactors := g.getStoriesByType(release.Stories, StoryTypeRefactor)
	other := g.getStoriesByTypeExcluding(release.Stories, []string{StoryTypeFeature, StoryTypeBugfix, StoryTypeChore, StoryTypeRefactor})

	// Features section
	if len(features) > 0 {
		sb.WriteString("\n## Features\n\n")
		g.writeStories(&sb, features, opts)
	}

	// Bug Fixes section
	if len(bugfixes) > 0 {
		sb.WriteString("\n## Bug Fixes\n\n")
		g.writeStories(&sb, bugfixes, opts)
	}

	// Refactoring section
	if len(refactors) > 0 {
		sb.WriteString("\n## Refactoring\n\n")
		g.writeStories(&sb, refactors, opts)
	}

	// Maintenance section
	if len(chores) > 0 {
		sb.WriteString("\n## Maintenance\n\n")
		g.writeStories(&sb, chores, opts)
	}

	// Other section
	if len(other) > 0 {
		sb.WriteString("\n## Other Changes\n\n")
		g.writeStories(&sb, other, opts)
	}

	// Approval information
	if opts.IncludeApprovals && release.Approval != nil {
		sb.WriteString("\n## Approval\n\n")
		sb.WriteString(fmt.Sprintf("- **Status:** %s\n", release.Approval.Status))
		if release.Approval.ApprovedBy != "" {
			sb.WriteString(fmt.Sprintf("- **Approved by:** %s\n", release.Approval.ApprovedBy))
		}
		if release.Approval.ApprovedAt != nil {
			sb.WriteString(fmt.Sprintf("- **Approved at:** %s\n", release.Approval.ApprovedAt.Format(opts.DateFormat)))
		}
		if release.Approval.Comments != "" {
			sb.WriteString(fmt.Sprintf("- **Comments:** %s\n", release.Approval.Comments))
		}
	}

	// Footer with generation info
	sb.WriteString("\n---\n")
	sb.WriteString(fmt.Sprintf("*Generated by OpenExec on %s*\n", time.Now().Format(opts.DateFormat)))

	return sb.String(), nil
}

// GenerateJSON generates a structured changelog in JSON format.
func (g *ChangelogGenerator) GenerateJSON() (*ChangelogData, error) {
	release := g.manager.GetRelease()
	if release == nil {
		return nil, fmt.Errorf("no release defined")
	}

	data := &ChangelogData{
		Name:        release.Name,
		Version:     release.Version,
		Description: release.Description,
		Date:        release.CreatedAt,
		Git:         release.Git,
		Approval:    release.Approval,
		Sections:    make([]ChangelogSection, 0),
	}

	// Group stories by type
	typeMap := map[string]string{
		StoryTypeFeature:  "Features",
		StoryTypeBugfix:   "Bug Fixes",
		StoryTypeRefactor: "Refactoring",
		StoryTypeChore:    "Maintenance",
	}

	for storyType, sectionName := range typeMap {
		stories := g.getStoriesByType(release.Stories, storyType)
		if len(stories) > 0 {
			section := ChangelogSection{
				Name:    sectionName,
				Type:    storyType,
				Stories: make([]ChangelogStory, 0, len(stories)),
			}

			for _, story := range stories {
				tasks := g.manager.GetTasksForStory(story.ID)
				clStory := ChangelogStory{
					ID:       story.ID,
					Title:    story.Title,
					Type:     story.StoryType,
					Status:   story.Status,
					Git:      story.Git,
					Approval: story.Approval,
					Tasks:    make([]ChangelogTask, 0, len(tasks)),
				}

				for _, task := range tasks {
					clStory.Tasks = append(clStory.Tasks, ChangelogTask{
						ID:       task.ID,
						Title:    task.Title,
						Type:     task.TaskType,
						Status:   task.Status,
						Git:      task.Git,
						Approval: task.Approval,
					})
				}

				section.Stories = append(section.Stories, clStory)
			}

			data.Sections = append(data.Sections, section)
		}
	}

	return data, nil
}

// ChangelogData represents structured changelog data.
type ChangelogData struct {
	Name        string             `json:"name"`
	Version     string             `json:"version"`
	Description string             `json:"description,omitempty"`
	Date        time.Time          `json:"date"`
	Git         *ReleaseGitInfo    `json:"git,omitempty"`
	Approval    *ApprovalInfo      `json:"approval,omitempty"`
	Sections    []ChangelogSection `json:"sections"`
}

// ChangelogSection represents a section of the changelog.
type ChangelogSection struct {
	Name    string           `json:"name"`
	Type    string           `json:"type"`
	Stories []ChangelogStory `json:"stories"`
}

// ChangelogStory represents a story in the changelog.
type ChangelogStory struct {
	ID       string          `json:"id"`
	Title    string          `json:"title"`
	Type     string          `json:"type"`
	Status   string          `json:"status"`
	Git      *StoryGitInfo   `json:"git,omitempty"`
	Approval *ApprovalInfo   `json:"approval,omitempty"`
	Tasks    []ChangelogTask `json:"tasks"`
}

// ChangelogTask represents a task in the changelog.
type ChangelogTask struct {
	ID       string        `json:"id"`
	Title    string        `json:"title"`
	Type     string        `json:"type"`
	Status   string        `json:"status"`
	Git      *TaskGitInfo  `json:"git,omitempty"`
	Approval *ApprovalInfo `json:"approval,omitempty"`
}

func (g *ChangelogGenerator) getStoriesByType(storyIDs []string, storyType string) []*Story {
	var stories []*Story
	for _, id := range storyIDs {
		story := g.manager.GetStory(id)
		if story != nil && story.StoryType == storyType {
			stories = append(stories, story)
		}
	}
	// Sort by priority then ID
	sort.Slice(stories, func(i, j int) bool {
		if stories[i].Priority != stories[j].Priority {
			return stories[i].Priority < stories[j].Priority
		}
		return stories[i].ID < stories[j].ID
	})
	return stories
}

func (g *ChangelogGenerator) getStoriesByTypeExcluding(storyIDs []string, excludeTypes []string) []*Story {
	excludeMap := make(map[string]bool)
	for _, t := range excludeTypes {
		excludeMap[t] = true
	}

	var stories []*Story
	for _, id := range storyIDs {
		story := g.manager.GetStory(id)
		if story != nil && !excludeMap[story.StoryType] {
			stories = append(stories, story)
		}
	}
	sort.Slice(stories, func(i, j int) bool {
		if stories[i].Priority != stories[j].Priority {
			return stories[i].Priority < stories[j].Priority
		}
		return stories[i].ID < stories[j].ID
	})
	return stories
}

func (g *ChangelogGenerator) writeStories(sb *strings.Builder, stories []*Story, opts *ChangelogOptions) {
	for _, story := range stories {
		// Story header
		sb.WriteString(fmt.Sprintf("### %s: %s\n\n", story.ID, story.Title))

		// Git info
		if opts.IncludeCommits && story.Git != nil {
			if story.Git.Branch != "" {
				sb.WriteString(fmt.Sprintf("**Branch:** `%s`\n", story.Git.Branch))
			}
			if story.Git.MergeCommit != "" {
				commitLink := story.Git.MergeCommit
				if opts.RepoURL != "" {
					commitLink = fmt.Sprintf("[%s](%s/commit/%s)", story.Git.MergeCommit[:7], opts.RepoURL, story.Git.MergeCommit)
				}
				sb.WriteString(fmt.Sprintf("**Merge commit:** %s\n", commitLink))
			}
			sb.WriteString("\n")
		}

		// Tasks
		if opts.IncludeTasks {
			tasks := g.manager.GetTasksForStory(story.ID)
			if len(tasks) > 0 {
				sb.WriteString("**Tasks:**\n")
				for _, task := range tasks {
					status := statusEmoji(task.Status)
					sb.WriteString(fmt.Sprintf("- %s %s: %s\n", status, task.ID, task.Title))

					// Task commits
					if opts.IncludeCommits && task.Git != nil && len(task.Git.Commits) > 0 {
						commits := make([]string, 0, len(task.Git.Commits))
						for _, hash := range task.Git.Commits {
							shortHash := hash
							if len(hash) > 7 {
								shortHash = hash[:7]
							}
							if opts.RepoURL != "" {
								commits = append(commits, fmt.Sprintf("[`%s`](%s/commit/%s)", shortHash, opts.RepoURL, hash))
							} else {
								commits = append(commits, fmt.Sprintf("`%s`", shortHash))
							}
						}
						sb.WriteString(fmt.Sprintf("  - Commits: %s\n", strings.Join(commits, ", ")))
					}
				}
				sb.WriteString("\n")
			}
		}

		// Approval info
		if opts.IncludeApprovals && story.Approval != nil && story.Approval.Status == ApprovalApproved {
			sb.WriteString(fmt.Sprintf("**Approved by:** %s on %s\n\n",
				story.Approval.ApprovedBy,
				story.Approval.ApprovedAt.Format(opts.DateFormat)))
		}
	}
}

func statusEmoji(status string) string {
	switch status {
	case "done", "completed":
		return "[x]"
	case "in_progress":
		return "[-]"
	case "failed":
		return "[!]"
	default:
		return "[ ]"
	}
}

// GenerateReleaseNotes generates release notes suitable for GitHub/GitLab releases.
func (g *ChangelogGenerator) GenerateReleaseNotes(opts *ChangelogOptions) (string, error) {
	if opts == nil {
		opts = DefaultChangelogOptions()
	}

	release := g.manager.GetRelease()
	if release == nil {
		return "", fmt.Errorf("no release defined")
	}

	var sb strings.Builder

	// Brief header
	if release.Description != "" {
		sb.WriteString(fmt.Sprintf("%s\n\n", release.Description))
	}

	// Group by type
	features := g.getStoriesByType(release.Stories, StoryTypeFeature)
	bugfixes := g.getStoriesByType(release.Stories, StoryTypeBugfix)

	// Features
	if len(features) > 0 {
		sb.WriteString("## What's New\n\n")
		for _, story := range features {
			sb.WriteString(fmt.Sprintf("* **%s** - %s\n", story.ID, story.Title))
		}
		sb.WriteString("\n")
	}

	// Bug fixes
	if len(bugfixes) > 0 {
		sb.WriteString("## Bug Fixes\n\n")
		for _, story := range bugfixes {
			sb.WriteString(fmt.Sprintf("* **%s** - %s\n", story.ID, story.Title))
		}
		sb.WriteString("\n")
	}

	// All other stories
	others := g.getStoriesByTypeExcluding(release.Stories, []string{StoryTypeFeature, StoryTypeBugfix})
	if len(others) > 0 {
		sb.WriteString("## Other Changes\n\n")
		for _, story := range others {
			sb.WriteString(fmt.Sprintf("* **%s** - %s\n", story.ID, story.Title))
		}
		sb.WriteString("\n")
	}

	return sb.String(), nil
}
